import { MemberMonthlyStats } from "@/lib/househub";

interface ReportShareCardProps {
  stats: MemberMonthlyStats;
  monthName: string;
}

const ReportShareCard = ({ stats, monthName }: ReportShareCardProps) => {
  return (
    <div 
      id="report-share-card"
      className="w-[360px] bg-white text-slate-900 overflow-hidden font-sans border border-slate-200 shadow-xl"
      style={{ position: 'fixed', left: '-1000px', top: '0' }}
    >
      {/* Header */}
      <div className="bg-[#770042] p-6 text-white text-center">
        <h1 className="text-2xl font-black uppercase tracking-widest flex items-center justify-center gap-2">
          🏠 NusaNest
        </h1>
        <p className="text-[10px] font-bold opacity-80 uppercase tracking-[0.2em] mt-1">
          Universitas Nusa Putra Student Housing
        </p>
      </div>

      {/* Body */}
      <div className="p-8">
        <div className="flex flex-col items-center mb-8 border-b border-slate-100 pb-6">
          <div className="w-16 h-16 rounded-2xl bg-[#770042] text-white flex items-center justify-center text-2xl font-black mb-3">
            {stats.memberName[0]}
          </div>
          <h2 className="text-xl font-black text-[#770042]">{stats.memberName}</h2>
          <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mt-1">
            {monthName} Performance Report
          </p>
        </div>

        <div className="space-y-4">
          <div className="flex items-center justify-between p-3 rounded-xl bg-slate-50">
            <span className="flex items-center gap-2 font-bold text-sm">
              <span>🧹</span> Cleaning
            </span>
            <div className="flex items-center gap-2">
              <span className="text-sm font-bold">{stats.cleaning.completed} / {Math.round(stats.cleaning.expected)} turns</span>
              <span className={stats.cleaning.completed >= stats.cleaning.expected ? "text-green-600" : "text-red-500"}>
                {stats.cleaning.completed >= stats.cleaning.expected ? "✅" : "❌"}
              </span>
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1 pl-1">🛒 Supplies</p>
            {stats.supplies.map(s => (
              <div key={s.itemId} className="flex items-center justify-between p-3 rounded-xl bg-slate-50">
                <span className="flex items-center gap-2 font-bold text-sm">
                  <span>{s.itemIcon}</span> {s.itemLabel}
                </span>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-bold">{s.completed} / {Math.round(s.expected)}</span>
                  <span className={!s.missed ? "text-green-600" : "text-red-500"}>
                    {!s.missed ? "✅" : "❌"}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-slate-100 flex items-end justify-between">
          <div>
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Overall Score</p>
            <p className="text-3xl font-black text-[#770042]">{stats.overallScore}%</p>
          </div>
          <div className="text-right">
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">House Rank</p>
            <p className="text-xl font-black text-[#D4A373]">#{stats.rank} this month</p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-[#770042] py-4 px-6 text-white/60 text-[9px] font-bold uppercase tracking-[0.2em] text-center">
        Generated by NusaNest · Fair Shared Housing
      </div>
    </div>
  );
};

export default ReportShareCard;
